"""Cross-repository dependency graph generation for PeachTree.

The graph is local and provenance-driven. It reads owned-repo inventory,
dataset JSONL files, and manifests generated by PeachTree, then emits JSON,
Mermaid, or DOT maps without contacting external systems.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass, field
import json
from pathlib import Path
import re
from typing import Any

from .github_owned import OwnedGitHubConnector, OwnedRepo


@dataclass(frozen=True)
class GraphNode:
    id: str
    label: str
    kind: str
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class GraphEdge:
    source: str
    target: str
    relation: str
    reason: str = ""

    def to_dict(self) -> dict[str, str]:
        return asdict(self)


@dataclass
class DependencyGraph:
    nodes: dict[str, GraphNode] = field(default_factory=dict)
    edges: list[GraphEdge] = field(default_factory=list)

    def add_node(self, node: GraphNode) -> None:
        self.nodes[node.id] = node

    def add_edge(self, edge: GraphEdge) -> None:
        if edge.source == edge.target:
            return
        key = (edge.source, edge.target, edge.relation)
        existing = {(e.source, e.target, e.relation) for e in self.edges}
        if key not in existing:
            self.edges.append(edge)

    def to_dict(self) -> dict[str, Any]:
        return {
            "nodes": [node.to_dict() for node in sorted(self.nodes.values(), key=lambda n: n.id)],
            "edges": [edge.to_dict() for edge in self.edges],
            "node_count": len(self.nodes),
            "edge_count": len(self.edges),
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, sort_keys=True)

    def to_mermaid(self) -> str:
        lines = ["flowchart TD"]
        for node in sorted(self.nodes.values(), key=lambda n: n.id):
            lines.append(f'    {self._mermaid_id(node.id)}["{self._escape(node.label)}<br/>{node.kind}"]')
        for edge in self.edges:
            lines.append(
                f'    {self._mermaid_id(edge.source)} -->|{self._escape(edge.relation)}| {self._mermaid_id(edge.target)}'
            )
        return "\n".join(lines)

    def to_dot(self) -> str:
        lines = ["digraph PeachTree {", "  rankdir=LR;"]
        for node in sorted(self.nodes.values(), key=lambda n: n.id):
            lines.append(f'  "{node.id}" [label="{self._escape(node.label)}\\n{node.kind}"];')
        for edge in self.edges:
            lines.append(f'  "{edge.source}" -> "{edge.target}" [label="{self._escape(edge.relation)}"];')
        lines.append("}")
        return "\n".join(lines)

    @staticmethod
    def _mermaid_id(value: str) -> str:
        cleaned = re.sub(r"[^A-Za-z0-9_]", "_", value)
        if cleaned and cleaned[0].isdigit():
            cleaned = f"n_{cleaned}"
        return cleaned or "node"

    @staticmethod
    def _escape(value: str) -> str:
        return value.replace('"', "'").replace("\n", " ")


class DependencyGraphBuilder:
    """Builds local cross-repo and dataset dependency graphs."""

    def from_inputs(
        self,
        inventory_path: str | Path | None = None,
        dataset_dir: str | Path | None = None,
        manifest_dir: str | Path | None = None,
    ) -> DependencyGraph:
        graph = DependencyGraph()
        repos = self._read_repos(inventory_path) if inventory_path else []
        for repo in repos:
            self._add_repo(graph, repo)

        if dataset_dir:
            self._add_datasets(graph, Path(dataset_dir), repos)
        if manifest_dir:
            self._add_manifests(graph, Path(manifest_dir), repos)

        self._add_ecosystem_edges(graph)
        return graph

    def _read_repos(self, inventory_path: str | Path) -> list[OwnedRepo]:
        return OwnedGitHubConnector().read_inventory(inventory_path)

    def _add_repo(self, graph: DependencyGraph, repo: OwnedRepo) -> None:
        graph.add_node(
            GraphNode(
                id=f"repo:{repo.full_name}",
                label=repo.full_name,
                kind="repository",
                metadata=repo.to_dict(),
            )
        )

    def _add_datasets(self, graph: DependencyGraph, dataset_dir: Path, repos: list[OwnedRepo]) -> None:
        if not dataset_dir.exists():
            return
        repo_names = {repo.full_name for repo in repos}
        for path in sorted(dataset_dir.glob("*.jsonl")):
            dataset_id = f"dataset:{path.name}"
            graph.add_node(
                GraphNode(
                    id=dataset_id,
                    label=path.name,
                    kind="dataset",
                    metadata={"path": str(path)},
                )
            )
            source_repos: set[str] = set()
            for record in self._iter_jsonl(path):
                source_repo = record.get("source_repo")
                if isinstance(source_repo, str) and source_repo:
                    source_repos.add(source_repo)
                    if source_repo not in repo_names:
                        graph.add_node(GraphNode(id=f"repo:{source_repo}", label=source_repo, kind="repository"))
                    graph.add_edge(
                        GraphEdge(
                            source=f"repo:{source_repo}",
                            target=dataset_id,
                            relation="contributes_records",
                            reason="DatasetRecord.source_repo",
                        )
                    )

    def _add_manifests(self, graph: DependencyGraph, manifest_dir: Path, repos: list[OwnedRepo]) -> None:
        if not manifest_dir.exists():
            return
        repo_ids = {f"repo:{repo.full_name}": repo for repo in repos}
        for path in sorted(manifest_dir.glob("*.json")):
            try:
                data = json.loads(path.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                continue
            manifest_id = f"manifest:{path.name}"
            graph.add_node(
                GraphNode(
                    id=manifest_id,
                    label=path.name,
                    kind="manifest",
                    metadata={
                        "path": str(path),
                        "record_count": data.get("record_count", 0),
                        "source_count": data.get("source_count", 0),
                        "domain": data.get("domain", ""),
                    },
                )
            )
            dataset_path = data.get("dataset_path")
            if isinstance(dataset_path, str) and dataset_path:
                dataset_id = f"dataset:{Path(dataset_path).name}"
                graph.add_node(GraphNode(id=dataset_id, label=Path(dataset_path).name, kind="dataset"))
                graph.add_edge(GraphEdge(source=dataset_id, target=manifest_id, relation="has_manifest"))

            domain = str(data.get("domain", ""))
            for repo_id, repo in repo_ids.items():
                if repo.safe_dir_name == domain or repo.full_name == domain:
                    graph.add_edge(GraphEdge(source=repo_id, target=manifest_id, relation="described_by_manifest"))

    def _add_ecosystem_edges(self, graph: DependencyGraph) -> None:
        repo_nodes = [node for node in graph.nodes.values() if node.kind == "repository"]
        by_lower = {node.label.lower(): node for node in repo_nodes}

        def find(term: str) -> GraphNode | None:
            for label, node in by_lower.items():
                if term in label:
                    return node
            return None

        peachtree = find("peachtree")
        peachfuzz = find("peachfuzz")
        hancock = find("hancock")

        if peachtree and peachfuzz:
            graph.add_edge(
                GraphEdge(
                    source=peachtree.id,
                    target=peachfuzz.id,
                    relation="generates_training_datasets_for",
                    reason="0AI ecosystem convention",
                )
            )
        if peachtree and hancock:
            graph.add_edge(
                GraphEdge(
                    source=peachtree.id,
                    target=hancock.id,
                    relation="generates_training_datasets_for",
                    reason="0AI ecosystem convention",
                )
            )
        if peachfuzz and hancock:
            graph.add_edge(
                GraphEdge(
                    source=peachfuzz.id,
                    target=hancock.id,
                    relation="feeds_security_fuzzing_knowledge_to",
                    reason="0AI cybersecurity model ecosystem",
                )
            )

    @staticmethod
    def _iter_jsonl(path: Path) -> list[dict[str, Any]]:
        records: list[dict[str, Any]] = []
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            try:
                value = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(value, dict):
                records.append(value)
        return records
