"""Model-card generation for PeachTree datasets."""
from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class ModelCard:
    model_name: str
    dataset_path: str
    content: dict[str, Any]

    def to_json(self) -> str:
        return json.dumps(self.content, indent=2, sort_keys=True)

    def to_markdown(self) -> str:
        c = self.content
        lines = [
            f"# Model Card: {self.model_name}",
            "",
            "## Overview",
            "",
            f"- Dataset: `{c.get('dataset_path')}`",
            f"- Intended use: {c.get('intended_use')}",
            f"- Generated by: `{c.get('generated_by')}`",
            "",
            "## Dataset Summary",
            "",
        ]
        summary = c.get("dataset_summary", {})
        for key in ("record_count", "source_count", "domain", "builder_version"):
            if key in summary:
                lines.append(f"- {key}: `{summary[key]}`")

        lines += ["", "## Quality and Readiness", ""]
        quality = c.get("quality", {})
        for key in ("gate_passed", "readiness_level", "average_score", "min_score", "passed_records", "failed_records"):
            if key in quality:
                lines.append(f"- {key}: `{quality[key]}`")

        lines += ["", "## License and Compliance", ""]
        license_gate = c.get("license_gate", {})
        if license_gate:
            lines.append(f"- License gate passed: `{license_gate.get('passed')}`")
            lines.append(f"- Allowed records: `{license_gate.get('allowed_count')}`")
            lines.append(f"- Denied records: `{license_gate.get('denied_count')}`")
            lines.append(f"- Unknown records: `{license_gate.get('unknown_count')}`")
        else:
            lines.append("- No license gate report supplied.")

        lines += ["", "## Policy Pack", ""]
        policy = c.get("policy_pack", {})
        if policy:
            lines.append(f"- Policy pack: `{policy.get('pack', {}).get('name')}`")
            lines.append(f"- Passed: `{policy.get('passed')}`")
            lines.append(f"- Requires human review: `{policy.get('safety', {}).get('requires_human_review')}`")
        else:
            lines.append("- No policy-pack report supplied.")

        lines += [
            "",
            "## Limitations",
            "",
            "- Dataset quality gates are static checks and do not prove model safety.",
            "- Human review is required before downstream training.",
            "- License metadata must be verified against source repositories before commercial use.",
            "",
            "## Safety",
            "",
            "- PeachTree does not train models.",
            "- PeachTree does not upload datasets.",
            "- Reports are generated for review-first training governance.",
        ]
        return "\n".join(lines)


class ModelCardGenerator:
    """Generates Markdown or JSON model cards from PeachTree reports."""

    def generate(
        self,
        dataset_path: str | Path,
        model_name: str,
        manifest_path: str | Path | None = None,
        quality_report_path: str | Path | None = None,
        license_report_path: str | Path | None = None,
        policy_report_path: str | Path | None = None,
        intended_use: str = "Safe downstream AI model training review.",
    ) -> ModelCard:
        dataset = Path(dataset_path)
        manifest = self._read_json(manifest_path)
        quality = self._read_json(quality_report_path)
        license_gate = self._read_json(license_report_path)
        policy = self._read_json(policy_report_path)

        dataset_summary = {
            "dataset_path": str(dataset),
            "record_count": self._count_jsonl(dataset),
        }
        if manifest:
            dataset_summary.update(
                {
                    "source_count": manifest.get("source_count"),
                    "domain": manifest.get("domain"),
                    "builder_version": manifest.get("builder_version"),
                    "manifest_path": str(manifest_path),
                }
            )

        content = {
            "model_name": model_name,
            "dataset_path": str(dataset),
            "intended_use": intended_use,
            "generated_by": "PeachTree",
            "dataset_summary": dataset_summary,
            "quality": self._compact_quality(quality),
            "license_gate": self._compact_license(license_gate),
            "policy_pack": self._compact_policy(policy),
            "review_requirements": {
                "human_review_required": True,
                "verify_licenses_before_commercial_use": True,
                "no_training_performed_by_peachtree": True,
            },
        }
        return ModelCard(model_name=model_name, dataset_path=str(dataset), content=content)

    def write(self, card: ModelCard, output_path: str | Path, output_format: str = "markdown") -> Path:
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        fmt = output_format.strip().lower()
        if fmt == "json":
            out.write_text(card.to_json() + "\n", encoding="utf-8")
        elif fmt == "markdown":
            out.write_text(card.to_markdown() + "\n", encoding="utf-8")
        else:
            raise ValueError(f"unsupported model card format: {output_format}")
        return out

    @staticmethod
    def _read_json(path: str | Path | None) -> dict[str, Any]:
        if not path:
            return {}
        p = Path(path)
        if not p.exists():
            return {}
        try:
            value = json.loads(p.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            return {}
        return value if isinstance(value, dict) else {}

    @staticmethod
    def _count_jsonl(path: Path) -> int:
        if not path.exists():
            return 0
        return sum(1 for line in path.read_text(encoding="utf-8").splitlines() if line.strip())

    @staticmethod
    def _compact_quality(report: dict[str, Any]) -> dict[str, Any]:
        keys = ("gate_passed", "readiness_level", "average_score", "min_score", "passed_records", "failed_records", "record_count")
        return {key: report[key] for key in keys if key in report}

    @staticmethod
    def _compact_license(report: dict[str, Any]) -> dict[str, Any]:
        keys = ("passed", "record_count", "allowed_count", "denied_count", "unknown_count", "license_counts")
        return {key: report[key] for key in keys if key in report}

    @staticmethod
    def _compact_policy(report: dict[str, Any]) -> dict[str, Any]:
        keys = ("pack", "passed", "gates", "safety")
        return {key: report[key] for key in keys if key in report}
