"""SBOM and provenance manifest generation for PeachTree release bundles."""
from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any

from .registry import DatasetRegistry, DatasetRegistryBuilder, sha256_file


@dataclass(frozen=True)
class SBOMDocument:
    name: str
    version: str
    created_at: str
    components: tuple[dict[str, Any], ...]
    provenance: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        return {
            "sbom_format": "PeachTree-SBOM",
            "sbom_version": "1.0",
            "name": self.name,
            "version": self.version,
            "created_at": self.created_at,
            "components": list(self.components),
            "provenance": self.provenance,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, sort_keys=True)

    def to_markdown(self) -> str:
        lines = [
            "# PeachTree SBOM / Provenance Manifest",
            "",
            f"- Name: `{self.name}`",
            f"- Version: `{self.version}`",
            f"- Created: `{self.created_at}`",
            f"- Components: `{len(self.components)}`",
            "",
            "| Component | Type | SHA-256 | Size | Path |",
            "|---|---|---|---:|---|",
        ]
        for component in self.components:
            lines.append(
                f"| `{component['name']}` | `{component['type']}` | `{component['sha256'][:16]}...` | {component['size_bytes']} | `{component['path']}` |"
            )
        lines += [
            "",
            "## Provenance",
            "",
            f"- Generated by: `{self.provenance.get('generated_by')}`",
            f"- Source registry: `{self.provenance.get('source_registry', '')}`",
            f"- Local only: `{self.provenance.get('local_only')}`",
            f"- No model training: `{self.provenance.get('does_not_train_models')}`",
        ]
        return "\n".join(lines)


class SBOMGenerator:
    """Generates SBOM/provenance manifests from registries or file paths."""

    def from_registry(
        self,
        registry: DatasetRegistry,
        source_registry: str | None = None,
        generated_by: str = "PeachTree",
    ) -> SBOMDocument:
        components = tuple(
            {
                "name": artifact.name,
                "type": artifact.kind,
                "path": artifact.path,
                "sha256": artifact.sha256,
                "size_bytes": artifact.size_bytes,
                "metadata": artifact.metadata,
            }
            for artifact in registry.artifacts
        )
        return SBOMDocument(
            name=registry.name,
            version=registry.version,
            created_at=datetime.now(timezone.utc).isoformat(),
            components=components,
            provenance={
                "generated_by": generated_by,
                "source_registry": source_registry or "",
                "local_only": True,
                "does_not_train_models": True,
                "does_not_upload_datasets": True,
                "review_required": True,
                "registry_metadata": registry.metadata,
            },
        )

    def from_paths(self, paths: list[str | Path], name: str = "peachtree-release", version: str = "0.8.0") -> SBOMDocument:
        registry = DatasetRegistryBuilder().build(paths, name=name, version=version)
        return self.from_registry(registry)

    def write(
        self,
        sbom: SBOMDocument,
        output_path: str | Path,
        markdown_output: str | Path | None = None,
    ) -> tuple[Path, Path | None]:
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(sbom.to_json() + "\n", encoding="utf-8")
        md_path: Path | None = None
        if markdown_output:
            md_path = Path(markdown_output)
            md_path.parent.mkdir(parents=True, exist_ok=True)
            md_path.write_text(sbom.to_markdown() + "\n", encoding="utf-8")
        return out, md_path

    @staticmethod
    def read_registry(path: str | Path) -> DatasetRegistry:
        return DatasetRegistryBuilder().read(path)
