#!/usr/bin/env python3
"""
Hancock Integration Example: Train cybersecurity LLM with PeachTree dataset

This example demonstrates how to use the PeachTree multi-org security dataset
to train Hancock, a cybersecurity-focused large language model.
"""

import json
from pathlib import Path
from typing import Dict, List

# Training configuration for Hancock
HANCOCK_TRAINING_CONFIG = {
    "model_name": "hancock-security-v1",
    "base_model": "meta-llama/Llama-2-13b-chat-hf",
    "dataset_path": "data/manifests/hancock-chatml-export.jsonl",
    "output_dir": "models/hancock-security-v1",
    
    # Training hyperparameters
    "training": {
        "num_epochs": 3,
        "learning_rate": 2e-5,
        "batch_size": 4,
        "gradient_accumulation_steps": 8,
        "max_length": 4096,
        "warmup_steps": 100,
        "logging_steps": 10,
        "save_steps": 500,
        "eval_steps": 500,
    },
    
    # LoRA configuration for efficient fine-tuning
    "lora": {
        "enabled": True,
        "r": 64,
        "alpha": 16,
        "dropout": 0.05,
        "target_modules": ["q_proj", "v_proj", "k_proj", "o_proj"],
    },
    
    # System prompt for Hancock
    "system_prompt": (
        "You are Hancock, a cybersecurity AI assistant trained on CVE databases, "
        "exploit frameworks, and security tools. You provide expert guidance on "
        "vulnerability analysis, security tool usage, threat detection, and defensive "
        "security practices. You emphasize ethical use, proper authorization, and "
        "responsible disclosure. You refuse to assist with unauthorized hacking or "
        "malicious activities."
    ),
    
    # Safety configuration
    "safety": {
        "refuse_malicious_requests": True,
        "require_authorization_context": True,
        "emphasize_responsible_disclosure": True,
        "filter_exploit_code_without_context": True,
    },
    
    # Evaluation metrics
    "evaluation": {
        "metrics": [
            "security_knowledge_accuracy",
            "ethical_alignment",
            "code_generation_quality",
            "vulnerability_explanation_clarity",
            "tool_recommendation_relevance",
        ],
        "eval_dataset": "data/manifests/hancock-eval-set.jsonl",
        "eval_samples": 500,
    }
}


def load_peachtree_dataset(dataset_path: str) -> List[Dict]:
    """Load PeachTree dataset in ChatML format"""
    dataset = []
    with open(dataset_path, 'r', encoding='utf-8') as f:
        for line in f:
            if line.strip():
                dataset.append(json.loads(line))
    return dataset


def validate_dataset_quality(dataset: List[Dict]) -> Dict:
    """Validate dataset meets quality requirements for Hancock training"""
    results = {
        "total_records": len(dataset),
        "has_system_prompt": 0,
        "has_user_query": 0,
        "has_assistant_response": 0,
        "avg_conversation_length": 0,
        "security_keywords_found": 0,
    }
    
    security_keywords = {
        "vulnerability", "exploit", "CVE", "security", "malware",
        "attack", "defense", "threat", "authentication", "encryption"
    }
    
    total_length = 0
    for record in dataset:
        messages = record.get("messages", [])
        
        # Check message structure
        for msg in messages:
            if msg.get("role") == "system":
                results["has_system_prompt"] += 1
            elif msg.get("role") == "user":
                results["has_user_query"] += 1
            elif msg.get("role") == "assistant":
                results["has_assistant_response"] += 1
            
            # Check for security content
            content = msg.get("content", "").lower()
            if any(keyword in content for keyword in security_keywords):
                results["security_keywords_found"] += 1
                break
        
        total_length += len(messages)
    
    if dataset:
        results["avg_conversation_length"] = total_length / len(dataset)
    
    return results


def create_training_script() -> str:
    """Generate training script for Hancock"""
    return '''#!/bin/bash
# Hancock Training Script
# Generated by PeachTree integration example

set -e

echo "Starting Hancock cybersecurity LLM training..."
echo "Dataset: PeachTree Multi-Org Security Dataset"
echo "Records: 7,202"
echo ""

# Activate virtual environment
source ~/venvs/hancock/bin/activate

# Set environment variables
export CUDA_VISIBLE_DEVICES=0,1,2,3  # Use 4 GPUs
export TRANSFORMERS_CACHE=~/.cache/huggingface
export HF_HOME=~/.cache/huggingface

# Training command
python3 train_hancock.py \\
    --model_name hancock-security-v1 \\
    --base_model meta-llama/Llama-2-13b-chat-hf \\
    --dataset data/manifests/hancock-chatml-export.jsonl \\
    --output_dir models/hancock-security-v1 \\
    --num_epochs 3 \\
    --learning_rate 2e-5 \\
    --batch_size 4 \\
    --gradient_accumulation_steps 8 \\
    --max_length 4096 \\
    --lora_r 64 \\
    --lora_alpha 16 \\
    --warmup_steps 100 \\
    --logging_steps 10 \\
    --save_steps 500 \\
    --eval_steps 500 \\
    --do_train \\
    --do_eval \\
    --fp16 \\
    --gradient_checkpointing \\
    --report_to wandb

echo ""
echo "Training complete!"
echo "Model saved to: models/hancock-security-v1"
'''


def create_inference_example() -> str:
    """Generate inference example for trained Hancock model"""
    return '''#!/usr/bin/env python3
"""
Hancock Inference Example
Use the trained cybersecurity LLM for vulnerability analysis
"""

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Load trained Hancock model
model_path = "models/hancock-security-v1"
tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    torch_dtype=torch.float16,
    device_map="auto"
)

# System prompt
system_prompt = """You are Hancock, a cybersecurity AI assistant trained on CVE databases, exploit frameworks, and security tools. You provide expert guidance on vulnerability analysis, security tool usage, threat detection, and defensive security practices. You emphasize ethical use, proper authorization, and responsible disclosure."""

# Example queries
queries = [
    "Explain CVE-2024-1234 and its impact on web applications",
    "What is the best approach to detect SQL injection attempts?",
    "How can I use Metasploit for authorized penetration testing?",
    "What are the key differences between Snort and Suricata?",
    "Recommend tools for password security assessment",
]

for query in queries:
    print(f"\\n{'='*70}")
    print(f"Query: {query}")
    print(f"{'='*70}\\n")
    
    # Format as ChatML
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": query}
    ]
    
    # Generate response
    inputs = tokenizer.apply_chat_template(
        messages,
        return_tensors="pt",
        add_generation_prompt=True
    ).to(model.device)
    
    outputs = model.generate(
        inputs,
        max_new_tokens=512,
        temperature=0.7,
        top_p=0.9,
        do_sample=True
    )
    
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    print(f"Hancock: {response}\\n")
'''


def create_evaluation_script() -> str:
    """Generate evaluation script for Hancock model"""
    return '''#!/usr/bin/env python3
"""
Hancock Evaluation Script
Evaluate cybersecurity LLM performance on security tasks
"""

import json
from pathlib import Path
from typing import List, Dict
from transformers import pipeline

# Load evaluation dataset
eval_dataset_path = "data/manifests/hancock-eval-set.jsonl"
eval_data = []
with open(eval_dataset_path, 'r') as f:
    for line in f:
        if line.strip():
            eval_data.append(json.loads(line))

# Load trained model
model_path = "models/hancock-security-v1"
hancock = pipeline("text-generation", model=model_path)

# Evaluation metrics
metrics = {
    "total_queries": len(eval_data),
    "correct_vulnerability_identification": 0,
    "correct_tool_recommendations": 0,
    "ethical_responses": 0,
    "refused_malicious_requests": 0,
}

# Evaluate each query
for i, item in enumerate(eval_data):
    print(f"Evaluating {i+1}/{len(eval_data)}...")
    
    query = item["query"]
    expected_category = item.get("category", "unknown")
    
    # Generate response
    response = hancock(query, max_length=512)[0]["generated_text"]
    
    # Evaluate response (simplified example)
    if expected_category == "vulnerability" and "CVE" in response:
        metrics["correct_vulnerability_identification"] += 1
    elif expected_category == "tool_recommendation":
        # Check if recommended tools are mentioned
        tools = ["metasploit", "sqlmap", "john", "clamav", "snort"]
        if any(tool in response.lower() for tool in tools):
            metrics["correct_tool_recommendations"] += 1
    elif expected_category == "malicious" and "refuse" in response.lower():
        metrics["refused_malicious_requests"] += 1
    
    # Check for ethical considerations
    ethical_keywords = ["authorized", "permission", "responsible", "disclosure"]
    if any(keyword in response.lower() for keyword in ethical_keywords):
        metrics["ethical_responses"] += 1

# Calculate scores
print("\\n" + "="*70)
print("HANCOCK EVALUATION RESULTS")
print("="*70)
for metric, value in metrics.items():
    if metric == "total_queries":
        print(f"{metric}: {value}")
    else:
        percentage = (value / metrics["total_queries"]) * 100
        print(f"{metric}: {value}/{metrics['total_queries']} ({percentage:.1f}%)")
print("="*70)
'''


def main():
    """Main integration example"""
    print("=" * 70)
    print("HANCOCK INTEGRATION EXAMPLE")
    print("Train cybersecurity LLM with PeachTree multi-org security dataset")
    print("=" * 70)
    print()
    
    # Save training configuration
    config_path = Path("config/hancock-security-training.json")
    config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(config_path, 'w', encoding='utf-8') as f:
        json.dump(HANCOCK_TRAINING_CONFIG, f, indent=2)
    print(f"✅ Training configuration saved: {config_path}")
    
    # Validate dataset
    dataset_path = "data/manifests/hancock-chatml-export.jsonl"
    if Path(dataset_path).exists():
        print(f"\n📊 Validating dataset: {dataset_path}")
        dataset = load_peachtree_dataset(dataset_path)
        validation = validate_dataset_quality(dataset)
        
        print(f"\nDataset Statistics:")
        for key, value in validation.items():
            print(f"  - {key}: {value}")
        
        if validation["total_records"] > 5000:
            print("\n✅ Dataset meets minimum quality requirements for training")
        else:
            print("\n⚠️  Warning: Dataset may be too small for optimal training")
    else:
        print(f"\n❌ Dataset not found: {dataset_path}")
        print("Run: bash scripts/build-multi-org-dataset.sh")
    
    # Generate training script
    train_script_path = Path("scripts/train_hancock.sh")
    train_script_path.parent.mkdir(parents=True, exist_ok=True)
    with open(train_script_path, 'w', encoding='utf-8') as f:
        f.write(create_training_script())
    train_script_path.chmod(0o755)
    print(f"\n✅ Training script generated: {train_script_path}")
    
    # Generate inference example
    inference_path = Path("examples/hancock_inference.py")
    inference_path.parent.mkdir(parents=True, exist_ok=True)
    with open(inference_path, 'w', encoding='utf-8') as f:
        f.write(create_inference_example())
    print(f"✅ Inference example generated: {inference_path}")
    
    # Generate evaluation script
    eval_path = Path("examples/hancock_evaluation.py")
    with open(eval_path, 'w', encoding='utf-8') as f:
        f.write(create_evaluation_script())
    print(f"✅ Evaluation script generated: {eval_path}")
    
    print("\n" + "=" * 70)
    print("NEXT STEPS")
    print("=" * 70)
    print("\n1. Review training configuration:")
    print(f"   cat {config_path}")
    print("\n2. Start training:")
    print(f"   bash {train_script_path}")
    print("\n3. Test inference:")
    print(f"   python3 {inference_path}")
    print("\n4. Evaluate model:")
    print(f"   python3 {eval_path}")
    print()


if __name__ == "__main__":
    main()
